spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/realms/splash/protocol/openid-connect/certs

server:
  port: ${USER_SERVICE_PORT}
  error:
    include-message: always

