spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${CONFIGURATION_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    generate-ddl: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${AUTHORIZATION_SERVER_PORT}
          jwk-set-uri: http://localhost:${AUTHORIZATION_SERVER_PORT}/oauth2/jwks

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
    template:
      default-topic: topic

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
      debug: true
    protocol: smtps

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${REGISTRY_SERVICE_PORT}/eureka

server:
  port: ${NOTIFICATION_SERVICE_PORT}