spring:
  application:
    name: business-order-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${BUSINESS_ORDER_SERVICE_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${REGISTRY_SERVICE_PORT}/eureka

server:
  port: ${BUSINESS_ORDER_SERVICE_PORT}
