version: '3.1'

services:
  authorization-server:
    build:
      context: authorization-server/
    image: 'krayseer/authorization-server:${APPLICATION_VERSION}'
    container_name: authorization-server
    ports:
      - '${AUTHORIZATION_SERVER_PORT}:${AUTHORIZATION_SERVER_PORT}'

  business-order-service:
    build:
      context: business-order-service/
    image: 'krayseer/business-order-service:${APPLICATION_VERSION}'
    container_name: business-order-service
    ports:
      - '${BUSINESS_ORDER_SERVICE_PORT}:${BUSINESS_ORDER_SERVICE_PORT}'

  configuration-service:
    build:
      context: configuration-service/
    image: 'krayseer/configuration-service:${APPLICATION_VERSION}'
    container_name: configuration-service
    ports:
      - '${CONFIGURATION_SERVICE_PORT}:${CONFIGURATION_SERVICE_PORT}'

  gateway:
    build:
      context: gateway/
    image: 'krayseer/gateway:${APPLICATION_VERSION}'
    container_name: gateway
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'

  notification-service:
    build:
      context: notification-service/
    image: 'krayseer/notification-service:${APPLICATION_VERSION}'
    container_name: notification-service
    ports:
      - '${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}'

  order-service:
    build:
      context: order-service/
    image: 'krayseer/order-service:${APPLICATION_VERSION}'
    container_name: order-service
    ports:
      - '${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}'

  registry-service:
    build:
      context: registry-service/
    image: 'krayseer/registry-service:${APPLICATION_VERSION}'
    container_name: registry-service
    ports:
      - '${REGISTRY_SERVICE_PORT}:${REGISTRY_SERVICE_PORT}'

  service-of-services:
    build:
      context: service-of-services/
    image: 'krayseer/service-of-services:${APPLICATION_VERSION}'
    container_name: service-of-services
    ports:
      - '${SERVICE_OF_SERVICES_PORT}:${SERVICE_OF_SERVICES_PORT}'

  statistics:
    build:
      context: statistics/
    image: 'krayseer/statistics:${APPLICATION_VERSION}'
    container_name: statistics
    ports:
      - '${STATISTICS_PORT}:${STATISTICS_PORT}'

  storage-service:
    build:
      context: storage-service/
    image: 'krayseer/storage-service:${APPLICATION_VERSION}'
    container_name: storage-service
    ports:
      - '${STORAGE_SERVICE_PORT}:${STORAGE_SERVICE_PORT}'

  frontend:
    build:
      context: ui-sources/
    image: 'krayseer/splash-frontend:${APPLICATION_VERSION}'
    container_name: splash-frontend
    ports:
      - '4200:4200'