spring:
  application:
    name: configuration-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${CONFIGURATION_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    generate-ddl: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${AUTHORIZATION_SERVER_PORT}
          jwk-set-uri: http://localhost:${AUTHORIZATION_SERVER_PORT}/oauth2/jwks

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

server:
  port: ${CONFIGURATION_SERVICE_PORT}