yandex-storage-config:
  bucket-name: ${BUCKET_NAME}
  access-key-id: ${ACCESS_KEY_ID}
  secret-access-key: ${SECRET_KEY}

spring:
  application:
    name: storage-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${REGISTRY_SERVICE_PORT}/eureka

server:
  port: ${STORAGE_SERVICE_PORT}
